module.exports = Object([
  "clothing",
  //"homeopathy",
  "clothing accessories",
  "acoustics",
  "aviation",
  "air force",
  "aeronautic technology",
  "agriculture",
  "food",
  "animal husbandry",
  "mountaineering",
  "anatomy",
  "antique trade",
  "anthropology",
  "free diving",
  "heraldry",
  "archaeology",
  "architecture",
  //"archival studies",
  "archery",
  "arithmetic",
  "weapons",
  "interior design",
  "art",
  "martial arts",
  "crafts",
  //"artistic crafts",
  "visual arts",
  //"artillery",
  "insurance industry",
  "auction",
  "astrophysics",
  "astrology",
  "astronautics",
  "astronomy",
  "culture",
  "athletics",
  "wrestling and weightlifting",
  "automation",
  "motor vehicles",
  "motor racing",
  "air travel",
  "ballistics",
  "ballet",
  "banking",
  "baseball",
  "The Bible",
  "libraries",
  "billiard sports",
  "biochemistry",
  "biophysics",
  "biology",
  "biotechnology",
  //"bobsledding",
  "stock exchange",
  "botany",
  "bowling",
  "boxing",
  "do it yourself",
  //"bridge (card game)",
  "Buddhism",
  "hunting",
  //"CAD (computer aided design)",
  //"five-a-side football",
  //"soccer (US)",
  "footwear",
  "rowing",
  "singing",
  "coal mining",
  "cardiology",
  "cartography",
  "pottery",
  "chemistry",
  "inorganic chemistry",
  "organic chemistry",
  "surgery",
  "cycling",
  "film industry",
  "circus",
  "track cycling",
  //"cytology",
  "collecting",
  "trade",
  "electronic components",
  "music composition",
  "computer art",
  "computer graphics",
  "media and communication",
  "leather processing",
  "beauty products",
  //"cosmography",
  //"cricket",
  "crime",
  "Christianity",
  "news",
  "database",
  //"decoupage",
  "dermatology",
  //"teaching methodology",
  //"dietetics",
  "diplomacy",
  "law",
  //"non-criminal law",
  //"business and commercial law",
  //"international law",
  //"criminal law",
  //"private law",
  //"administrative law",
  "electronic storage",
  "illustration",
  "Judaism",
  "ecology",
  "e-commerce",
  "the economy",
  "construction industry",
  "publishing",
  "electricity",
  "electronics",
  //"electrotechnics",
  "e-mail",
  "embryology",
  "energy",
  "puzzles",
  //"enology",
  "entomology",
  "epigraphy",
  //"equitation",
  "ethics",
  "Islam",
  //"ethnology",
  "TV broadcasting",
  "evolution",
  "carpentry",
  "pharmaceuticals",
  "pharmacology",
  "trains",
  "philately",
  "philology",
  "philosophy",
  "finance",
  //"finance (private)",
  // "public financing",
  //"revenue services",
  "physics",
  //"atomic physics",
  "physiology",
  //"phytopathology",
  "folklore",
  "phonetics",
  "phonology",
  "American football",
  "photography",
  //"artistic photography",
  //"free climbing",
  "fruit growing",
  "cartoons and comic books",
  "art galleries",
  "gastronomy",
  "genealogy",
  "genetics",
  "geophysics",
  "geography",
  "geology",
  "geometry",
  "gardening",
  "toys",
  "card games",
  "games and toys",
  "jewelry",
  "the press",
  "journalism",
  //"go-karting",
  "golf",
  "graffiti",
  "grammar and syntax",
  "computer hardware",
  "hockey",
  "ice hockey",
  "hydraulics",
  "immunology",
  "business",
  "engraving",
  "industry",
  "aeronautics industry",
  "food industry",
  "automotive industry",
  "arms industry",
  "footwear industry",
  "ceramic industry",
  "chemical industry",
  "rail transport",
  "furniture industry",
  "motorcycle industry",
  "shipbuilding",
  "textile industry",
  "glass manufacturing",
  "industrial design",
  "computer science",
  "engineering",
  "aerospace engineering",
  "Internet",
  //"intranet",
  "equestrian sports",
  "institutions",
  "education",
  "ichthyology",
  "kayaking",
  "needlework",
  "job market",
  "legislation",
  "judo",
  "literature",
  "linguistics",
  "lithography",
  "liturgy",
  "lottery",
  //"animal slaughter",
  "knitting",
  "manufacturing",
  "watercraft and nautical navigation",
  "naval forces",
  "marketing",
  "mathematics",
  "mechanics",
  "public administration",
  "medicine",
  "alternative medicine",
  "data storage",
  "board games",
  "metallurgy",
  "meteorology",
  // "meter and prosody",
  "ophthalmology",
  "microbiology",
  "armed forces",
  "mineralogy",
  "mines",
  "government departments and ministries",
  "rocket science",
  "mythology",
  "furniture",
  "fashion",
  //"computer monitor",
  "motorcycling",
  //"powertrain design and engineering",
  "multimedia",
  "masonry",
  "museums",
  "music",
  "numismatics",
  "swimming",
  "occultism",
  "hydrography",
  "orthodontics",
  "oncology",
  "opera",
  "goldsmithing",
  "ornithology",
  "watchmaking",
  "orthopedics",
  "hospitals",
  "optics",
  "paleography",
  "paleontology",
  "paleozoology",
  "basketball",
  "handball",
  "water polo",
  "volleyball",
  "papyrology",
  "parapsychology",
  "Parliament and legislative bodies",
  "skating",
  "pedagogy",
  "classical music",
  "fishing",
  "sport fishing",
  "spearfishing",
  //"petrochemistry",
  //"petrochemicals",
  "table tennis",
  "painting",
  "glass painting",
  "poetry",
  "poker",
  "politics",
  "police",
  "postal service",
  "prehistory",
  "welfare",
  "computer processors",
  "perfumery",
  "computer programming",
  "office productivity software",
  "psychoanalysis",
  "psychiatry",
  "psychology",
  "advertising",
  "radio broadcasting",
  "radiology",
  "kitchen tools",
  "public relations",
  "religion",
  "information technology",
  "rhetoric",
  // "lacework",
  "restaurant industry",
  "robotics",
  "rugby",
  "health care",
  "tailoring",
  "chess",
  //"scenography",
  //"graphics card",
  "fencing",
  "skiing",
  "downhill skiing",
  "cross-country skiing",
  "water skiing",
  "STEM",
  "social science",
  "sculpture",
  "school systems",
  "forestry",
  "social services",
  "sexology",
  "sects",
  "security and public safety",
  //"iron metallurgy",
  "unions",
  "seismology",
  "operating systems",
  "mining industry",
  // "mushing",
  "sledding",
  "snowboard",
  "sociology",
  "softball",
  "software",
  "entertainment",
  "sports",
  "squash",
  "printing",
  "printers",
  "statistics",
  "history",
  "ancient history",
  "contemporary history",
  "medieval history",
  "modern history",
  "roads and traffic",
  "musical instruments",
  "hospitality facilities",
  "numismatics (study)",
  "scuba diving",
  "surfing",
  "theatre",
  "technical drawing",
  "technology",
  "telecommunications",
  "telephony",
  "telegraph",
  "television",
  "tennis",
  "theology",
  "thermohydraulics",
  "thermodynamics",
  "textiles",
  //"target-shooting",
  //"skeet shooting",
  "topography",
  "transportation",
  "trekking",
  "diving",
  "tourism",
  "crochet",
  "university",
  "city planning",
  "sailing",
  "veterinary science",
  "glassware",
  "video games",
  "wine industry",
  "volcanology",
  "windsurfing",
  "zoology",
  //"zootechnics",
  "bureaucratic terminology",
  "scientific terms",
  "technical terminology",
  "cosmetic industry",
  "gymnastics",
  //"rhythmic gymnastics",
  //"artistic gymnastics",
  //"lawn bowls",
  //"checkers",
  "science fiction",
  "accounting",
  "marine biology",
  "parachuting",
  "gambling",
  "karate",
  "typewriting",
  "shorthand",
  "Hinduism",
  "polo",
]);
